---
-   name: Update apt cache
    apt:
        update_cache: yes
        cache_valid_time: 3600

-   name: Install common packages
    apt:
        name:
            - curl
            - git
            - build-essential
            - python3-pip
        state: present

-   name: Set timezone
    timezone:
        name: Europe/Paris
