---
-   import_playbook: bootstrap.yml

-   hosts: all
    become: yes
    roles:
        - common
        - nodejs
        - bun

    tasks:
        -   name: Install git
            apt:
                name: git
                state: present
                update_cache: yes
